GET http://localhost:8000/api/hello

###

POST http://localhost:8000/api/encrypt
content-type: application/json

{
    "dek": "/eIqTqFEp3GimUezaCO1/R/EKmHgqjQLFX1EWqPknoI=",
    "iv": "4+v+r486s6eqknwY",
    "authorized_users": ["user1@gmail.com", "user2@gmail.com"]
}

###

POST http://localhost:8000/api/decrypt
content-type: application/json 

{
    "header": "CiQAOimRZU0Gt6rvBpBPT7pJotebX3JSS7M0F8DtTuYBARyE4XASewCyCHMS2div5FTZhmKNzYJeoSyOs3Fc0j4h-_cPkmUzj94z1mcsKHgObZwMVq1erJIr8pUoiOORREMxV7YwBH5XyLxmjLKidJsm8FjBXrkZVHwamDkcGI5_dxr8G2siajX7-8m-A7yT1FFQHiQ-oHFT_TBAZyTTI7xX5g=="
}
